version: '3.5'
services:
  dynamic-router:
    ports:
      - "8005:8005"
    volumes:
      - .:/var/www/html
      - /var/www/html/dynamic-router/
    build: .
    command: php -S dynamic-router:8005 index.php
    restart: always